"""Documentation vivante des stratégies du fonds.

Chaque stratégie réellement implémentée dans le code est décrite ici :
principe, facteurs utilisés, règles d'entrée/sortie, coûts, limites et
verdict d'évaluation OOS quand il existe. C'est l'onglet « Stratégies »
du terminal : le gérant voit concrètement en quoi consiste chaque
stratégie, sans marketing.

Références : Dixon, Halperin & Bilokon, "Machine Learning in Finance"
(Springer 2020), chapitres 4-10.
"""

STRATEGIES = [
    {
        "id": "core_trend",
        "name": "60/40 + couche tendance (production, 90 % du capital)",
        "category": "Systématique multi-actifs",
        "chapter": "Chap. 2 §7.5 (moyennage de modèles), 6 §2.9-2.10 (GARCH, lissage), 7 (Kalman)",
        "principle": "Un socle de primes de risque (30 % S&P 500, 20 % Treasuries 7-10 ans) auquel on ajoute une couche de suivi de tendance long/short sur 20 ETF (actions, obligations, matières premières, devises). La tendance est quasi décorrélée du socle (corrélation ~0,05) et gagne surtout pendant les crises : elle divise le drawdown par deux.",
        "factors": ["TSMOM 12 mois (signe)", "Croisements EWMA 8/24, 16/48, 32/96", "Pente Kalman niveau+pente (t-stat)", "Vol GARCH(1,1) prévue", "Covariance EWMA rétrécie"],
        "rules": "Signal = moyenne des 3 tendances dans [-1, 1] · position = signal × vol cible / vol GARCH (risque égal par actif) · portefeuille tendance remis à 10 % de vol ex-ante, brut <= 200 % · rebalancement hebdomadaire, on ne bouge une ligne que si l'écart dépasse 25 % de la cible",
        "costs": "5 bps par unité de turnover · turnover ~9x/an · ~0,5 %/an de coûts",
        "strengths": "Validation 2020-2026 (jamais utilisée pour choisir) : Sharpe 1,04, max drawdown -10 % (60/40 : 0,78 et -21 %). Deflated Sharpe 93 % sur 18 essais.",
        "limits": "Vol plus faible que le 60/40 : en rendement brut il peut faire moins bien en marché haussier calme. Les tendances souffrent lors de retournements brutaux (V-shape). Socle US : biais de la décennie américaine.",
        "verdict_oos": "GAGNANT — branché dans le paper trading (sélection sur 2008-2019 uniquement)",
    },
    {
        "id": "crypto_trend",
        "name": "Crypto tendance long-only (production, 10 % du capital)",
        "category": "Crypto 24/7",
        "chapter": "Chap. 6-7 — mêmes briques que la couche tendance",
        "principle": "Même ensemble de tendances appliqué à 7 cryptos (BTC, ETH, XRP, LTC, ADA, BNB, DOGE). Uniquement long : quand la tendance est négative, la poche est en cash plutôt qu'à découvert (coût de financement et risque de squeeze).",
        "factors": ["Ensemble TSMOM / EWMA / Kalman", "Vol GARCH", "Covariance EWMA"],
        "rules": "Positions longues seulement, vol cible 25 %, brut <= 100 %, une ligne <= 50 % de la poche, rebalancement hebdomadaire",
        "costs": "20 bps par unité de turnover · turnover ~10x/an",
        "strengths": "Validation 2023-2026 : Sharpe 0,83, max drawdown -39 % contre -53 % pour le Bitcoin (2018-2022 : -37 % contre -77 %).",
        "limits": "Rendement brut inférieur au Bitcoin en marché haussier ; 9 ans d'historique seulement.",
        "verdict_oos": "GAGNANT — branché dans le paper trading (sélection sur 2018-2022 uniquement)",
    },
    {
        "id": "fx_carry_g10",
        "name": "Carry de change G10 (évalué, rejeté)",
        "category": "Devises",
        "chapter": "Prime de risque classique — parité des taux couverte",
        "principle": "Acheter les 3 devises du G10 aux taux courts les plus élevés et vendre les 3 aux taux les plus bas, via des termes de change roulés : on encaisse le différentiel de taux, au prix d'un risque de krach (2008).",
        "factors": ["Taux 3 mois OCDE (2 mois de retard de publication)", "Vol EWMA", "Filtre de tendance (variante)"],
        "rules": "Classement mensuel des différentiels contre USD · long 3 / short 3 · risque égal · vol cible 10 % · variante : une jambe est retirée si la tendance de la devise la contredit",
        "costs": "3 bps par unité de turnover (termes de change)",
        "strengths": "Quasi décorrélé du reste du fonds (corrélation ~0,1).",
        "limits": "Sharpe ~0 de 2006 à 2019 (taux proches de zéro partout après 2008) ; ajouté à la stratégie retenue, il dégrade le Sharpe de développement (0,99 -> 0,75-0,80).",
        "verdict_oos": "DÉSACTIVÉ — ne bat pas la stratégie retenue sur la période de développement (banc d'évaluation, section carry)",
    },
    {
        "id": "momentum",
        "name": "Momentum multi-actifs",
        "category": "Systématique",
        "chapter": "Chap. 6 — momentum cross-sectionnel",
        "principle": "Acheter les actifs dont le rendement passé (lookback 90j) est le plus fort, vendre les plus faibles. L'idée : les tendances persistent à horizon de semaines.",
        "factors": ["Rendement passé 90j", "Volatilité 30j (pondération inverse)"],
        "rules": "Classement des N actifs par score de momentum · top 20% long, bottom 20% short · poids inversement proportionnels à la vol · rebalancement hebdomadaire",
        "costs": "7 bps par unité de turnover (2 commission + 5 slippage)",
        "strengths": "Simple, robuste sur 40 ans de données, peu de paramètres",
        "limits": "Souffre en régime de mean-reversion violente (cracks type 2020)",
        "verdict_oos": "Sharpe OOS walk-forward positif sur FRED long (évalué phase 2)",
    },
    {
        "id": "meanrev",
        "name": "Mean-reversion z-score",
        "category": "Systématique",
        "chapter": "Chap. 6 — retour à la moyenne",
        "principle": "Parier que les actifs qui s'écartent fortement de leur moyenne récente (z-score > 2) reviennent vers elle.",
        "factors": ["Z-score du prix sur 30j", "Distance à la moyenne 60j"],
        "rules": "z > +2 → short · z < -2 → long · sortie au croisement de la moyenne · stop à 2x l'écart d'entrée",
        "costs": "7 bps/unité de turnover",
        "strengths": "Excellent en régime de range (marchés choppy)",
        "limits": "Dangereux en tendance forte (se faire retourner), drawdowns rapides",
        "verdict_oos": "Positif sur données synthétiques, marginal sur FRED réel",
    },
    {
        "id": "multifactor",
        "name": "Multi-facteurs (mom + MR + trend + vol)",
        "category": "Systématique",
        "chapter": "Chap. 6 — combinaison de facteurs",
        "principle": "Combiner momentum, mean-reversion, qualité de tendance (R²) et régime de vol dans un score composite égal-pondéré.",
        "factors": ["Momentum 60j", "Z-score 30j", "R² de tendance 90j", "Vol relative"],
        "rules": "Score composite par actif · long/short top/bottom 25% · vol target 10%",
        "costs": "7 bps/unité de turnover",
        "strengths": "Diversifié entre styles, plus stable qu'un seul facteur",
        "limits": "Un facteur peut en annuler un autre selon le régime",
        "verdict_oos": "Comparable au momentum seul sur FRED",
    },
    {
        "id": "regime-momentum",
        "name": "Momentum filtré par régime (HMM)",
        "category": "Régime-conditionné",
        "chapter": "Chap. 7 — HMM à états cachés",
        "principle": "Un HMM 3-états (Baum-Welch) classe le marché en tendance haussière / baissière / incertain. Le momentum n'est actif qu'en régime identifié tendanciel.",
        "factors": ["Probabilités a posteriori HMM 3 états", "Momentum 60j"],
        "rules": "Si p(régime haussier) > 0.5 → momentum long-only · si p(baissier) > 0.5 → short-only · sinon flat",
        "costs": "7 bps/unité de turnover",
        "strengths": "Évite les whipsaws en régime incertain",
        "limits": "Le HMM apprend ses états sur l'historique — risque de re-labeling",
        "verdict_oos": "Évalué phase 1 : améliore la discipline du momentum",
    },
    {
        "id": "risk-managed",
        "name": "Momentum risk-managed (ancien paper, retiré)",
        "category": "Régime-conditionné",
        "chapter": "Chap. 7 + gestion du risque",
        "principle": "Momentum + désactivation quand la vol réalisée dépasse un percentile historique + drawdown guard (déleverage à -5%, flat à -12%).",
        "factors": ["Momentum 90j", "Vol réalisée 30j vs seuil 60%", "Drawdown de l'équity"],
        "rules": "Momentum standard tant que vol < seuil · levier réduit linéairement au-dessus · stop total au drawdown 12%",
        "costs": "7 bps/unité de turnover",
        "strengths": "Protège le capital dans les krachs, drawdown maîtrisé",
        "limits": "Peut rater le rebond post-crack (flat forcé)",
        "verdict_oos": "DÉSACTIVÉ — banc ETF 2008-2026 : Sharpe -0,02 en développement, 0,14 en validation",
    },
    {
        "id": "crypto-risk-managed",
        "name": "Crypto régime risk-managed (ancien paper, retiré)",
        "category": "Crypto",
        "chapter": "Chap. 7 adapté crypto",
        "principle": "Sur l'univers Binance nettoyé (23 actifs) : momentum conditionné au régime de vol crypto, sizing réduit, drawdown guard strict.",
        "factors": ["Momentum 90j", "Vol crypto 30j", "Drawdown"],
        "rules": "Top 4 momentum si vol < 60% annualisée · exposition 0.5x sinon · drawdown guard identique",
        "costs": "7 bps/unité de turnover",
        "strengths": "Taille les positions pour survivre aux crashes -70%",
        "limits": "Verdict honnête : AUCUN edge validé OOS sur crypto (ridge -0.33, momentum -0.24) — maintenu en paper pour la mesure de risque, pas pour le rendement",
        "verdict_oos": "DÉSACTIVÉ — validation 2023-2026 : Sharpe 0,04 (remplacé par la tendance long-only)",
    },
    {
        "id": "ridge-ml",
        "name": "Ridge ML cross-sectionnel (ancien moteur, retiré)",
        "category": "Machine Learning",
        "chapter": "Chap. 4 — régression ridge, classement",
        "principle": "Ré-entraînement glissant d'une régression ridge (équation normale, numpy pur) sur 14 features causales (momentum multi-horizons, vol, z-score, R², drawdown, probas HMM, beta Kalman) pour prédire le rendement forward 21j demeané. Classement top-k long / bottom-k short.",
        "factors": ["14 features techniques causales", "Cible : rendement forward 21j demeané cross-sectionnellement"],
        "rules": "Ré-entraînement tous les 125 jours sur fenêtre 500j · top 20% long / bottom 20% short · λ=10 (robuste 1→100) · purge et embargo 10j entre train et test",
        "costs": "7 bps/unité de turnover",
        "strengths": "SEUL modèle à battre la baseline OOS : Sharpe +0.63 sur FRED 20 ans, 4 folds purgés, positif 3 folds/4 · test anti-fuite : cibles permutées → -0.50",
        "limits": "Edge mesuré sur une seule classe d'actifs (macro FRED), période 2005-2025",
        "verdict_oos": "DÉSACTIVÉ — sur 20 ETF négociables : Sharpe -0,22 (2008-2019) et -0,48 (2020-2026), drawdown -47 %. Le +0,63 initial venait d'un univers FRED de 8 séries dont certaines non négociables",
    },
    {
        "id": "feedforward",
        "name": "Réseau feedforward (désactivé)",
        "category": "Machine Learning",
        "chapter": "Chap. 8 — réseaux de neurones",
        "principle": "Petit réseau 14→16→1 (numpy pur, rétropropagation manuelle) sur les mêmes features que le ridge.",
        "factors": ["Mêmes 14 features que le ridge"],
        "rules": "Identiques au ridge (même cible, même classement)",
        "costs": "7 bps/unité de turnover",
        "strengths": "Capacité non-linéaire théorique",
        "limits": "Sharpe OOS +0.12 < ridge +0.63 : la non-linéarité n'apporte rien ici",
        "verdict_oos": "DÉSACTIVÉ — ne bat pas la baseline (règle non négociable)",
    },
    {
        "id": "autoencoder",
        "name": "Autoencodeur de features (désactivé)",
        "category": "Machine Learning",
        "chapter": "Chap. 8 — représentations apprises",
        "principle": "Compression des features en 5 dimensions latentes pour débruiter avant le ridge.",
        "factors": ["Représentation latente 5d des 14 features"],
        "rules": "Ridge sur l'espace latent",
        "costs": "7 bps/unité de turnover",
        "strengths": "Théoriquement débruite",
        "limits": "N'a pas amélioré l'OOS vs ridge brut",
        "verdict_oos": "DÉSACTIVÉ — pas d'amélioration démontrée",
    },
    {
        "id": "rl-allocation",
        "name": "Allocation RL : Q-learning / G-learning (désactivé)",
        "category": "Renforcement",
        "chapter": "Chap. 9-10 — apprentissage par renforcement",
        "principle": "G-learning : contrôle LQR probabiliste (u* = μ/(λσ²+η)) avec états de régime HMM. Q-learning tabulaire ε-greedy : états (régime, vol, levier) × 5 actions de levier.",
        "factors": ["Régime HMM", "Vol annualisée", "Levier courant"],
        "rules": "Ré-entraînement par fold walk-forward, actions bornées [-1, +1]",
        "costs": "7 bps/unité de turnover",
        "strengths": "G-learning : drawdown 50% → 15%",
        "limits": "G-learning : rendement écrasé, Sharpe 0.21 < ridge 0.63 · Q-learning : -0.15",
        "verdict_oos": "DÉSACTIVÉ — aucun ne bat la baseline (verdict documenté)",
    },
    {
        "id": "fx-carry",
        "name": "FX carry (exploration)",
        "category": "Forex",
        "chapter": "Chap. 6 — carry",
        "principle": "Long les devises à taux élevés, short celles à taux faibles (différentiel 3M), sur 6 paires majeures FRED ~24 ans.",
        "factors": ["Différentiel de taux 3M", "Trend de la paire"],
        "rules": "Pondération proportionnelle au différentiel de taux",
        "costs": "7 bps/unité de turnover",
        "strengths": "Classique, intuitif",
        "limits": "Risque de crash de carry (dérisquages violents)",
        "verdict_oos": "AUCUN edge OOS validé au 2026-09 — exploration uniquement",
    },
    {
        "id": "equities-ridge",
        "name": "Ridge actions + fondamentaux (documenté)",
        "category": "Machine Learning",
        "chapter": "Chap. 4 + données fondamentales",
        "principle": "Le ridge validé étendu aux 8 actions cotées du portefeuille fondamental (PLTR, NVDA, BRK-B, ASML, AMD, TSLA, JPM, MSFT) avec features fondamentales visibles à date (lag 45 jours anti-look-ahead).",
        "factors": ["Features prix identiques au ridge", "+ croissance revenue, marges, FCF yield (visibles à date)"],
        "rules": "Walk-forward identique au ridge, fenêtre dès la première publication fondamentale visible (fév. 2022)",
        "costs": "7 bps/unité de turnover",
        "strengths": "Méthodologie la plus propre possible (permutation test ~0 : pas de fuite)",
        "limits": "Résultat honnête : fondamentaux dégénèrent le ridge (0.17 vs 1.03 prix seul) — features annuelles trop statiques sur 8 actifs · le momentum domine 2024-2026",
        "verdict_oos": "NON RETENU pour le trading — documenté",
    },
]


def get_strategies() -> list[dict]:
    return STRATEGIES
